### ISSUE TITLE
Keystore generates cipher message that is too long

### ISSUE THREAD

**Issue by mrtestyboy781** [ChainSafe/bls-keystore#14]
If you generate keystore and then try to import it as an object
```
Keystore.fromObject(JSON.parse(keystore.stringify()));
```
It generates error:
`Error: .crypto.cipher.message: should match pattern "^([A-Fa-f0-9]{2}){32}$"`

For example, a generated keystore looks like
```
{
  "version": 4,
  "uuid": "9c2ed357-910f-4c0d-95be-3959abb7ba23",
  "path": "m/12381/3600/0/0/0",
  "pubkey": "0c71111d4d27fe2cf9a2163c48a75a2f715cf12bbb2b609a8d1a1a00d8f18f4d",
  "crypto": {
    "kdf": {
      "function": "pbkdf2",
      "params": {
        "dklen": 32,
        "c": 262144,
        "prf": "hmac-sha256",
        "salt": "ab057cd3192eff53fbe13dcd2aa91bdc000f12b44b26cbf0bdddd142c6c6b663"
      },
      "message": ""
    },
    "checksum": {
      "function": "sha256",
      "params": {},
      "message": "cc29ccff7e37dab8c2229360693b3bdd66e3d74d999b56fc52cb35a06022b3b6"
    },
    "cipher": {
      "function": "aes-128-ctr",
      "params": {
        "iv": "54492a730ca676c52eaf4712938e8356"
      },
      "message": "42c1608033a60f93e562a3bba591ebdffa772e8824331f4405f64388c277c29099487c77fb17325ef37be4cf19c24e5b"
    }
  }
}
```

It appears the cipher.message should be hashed?

**Comment by mrtestyboy781** [comment]
@wemeetagain - Can you verify this bug when able?

**Comment by wemeetagain** [comment]
@mrtestyboy781 thanks for reporting this.

The validation is pretty strict here, if you don't use a _real_ public key and private key, the lengths will probably be wrong.
The library doesn't check the validity of the pub/priv keys, but it does a sanity check on the length.

It looks like your private key is 48 bytes long here? We're expecting a 32 byte long private key.
It looks like your public key is 32 bytes long too?
Perhaps you swapped the order of the arguments when creating the keystore.

**Comment by wemeetagain** [comment]
We should probably add a verification step inside `Keystore.create` so that it isn't possible to create invalid keystores.

**Comment by mrtestyboy781** [comment]
You are totally right, I swapped the pubkey/private key arg on accident when constructing the keystore. 

Thank you for the help!
