### ISSUE TITLE
upgrade uuid (and other packages, probably)

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/bls-keystore#22]
when upgrading this package in https://github.com/chainsafe/bls-keygen-app, I saw the following warning

> warning @chainsafe/bls-keystore > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

We also have a few dependabot PRs that have popped up so it would probably be good to try and upgrade other deps where possible/needed.

**Comment by wemeetagain** [comment]
closing this since we've updated deps recently
