### ISSUE TITLE
using decrypt in promise.all

### ISSUE THREAD

**Issue by Dhuliang** [ChainSafe/bls-keystore#60]
trying to batch decrypt, but it takes the same amount of time as decrypt individually.
how do I get faster?

**Comment by nflaig** [comment]
`decrypt` is a synchronous / blocking operation, the only way to speed it up is to use worker threads.

Take a look at how we handle this in Lodestar, see [decryptKeystores](https://github.com/ChainSafe/lodestar/tree/unstable/packages/cli/src/cmds/validator/keymanager/decryptKeystores)

**Comment by Dhuliang** [comment]
use mutiple web workers works
